package frames;

import chisquaretest.Data;
import chisquaretest.TestChi;
import javax.swing.table.DefaultTableModel;

public class MainFrame extends javax.swing.JFrame {

    Data data = new Data();
    TestChi test = new TestChi(data);
    DefaultTableModel model;
    int n, m;
    double alfa;
    
    public MainFrame(String title) {
        super(title);
        initComponents();
        model = (DefaultTableModel) table.getModel(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        N = new javax.swing.JTextField();
        dimLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        M = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        dimButton = new javax.swing.JButton();
        calculateButton = new javax.swing.JButton();
        resLabel = new javax.swing.JLabel();
        pValLabel = new javax.swing.JLabel();
        pValLabel1 = new javax.swing.JLabel();
        pValText = new javax.swing.JTextField();
        resText = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        alfa_01 = new javax.swing.JRadioButton();
        alfa_05 = new javax.swing.JRadioButton();
        alfa_1 = new javax.swing.JRadioButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });

        dimLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dimLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dimLabel.setText("Insert Dimension");

        jLabel2.setText("X");

        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        dimButton.setText("Insert Dim.");
        dimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dimButtonActionPerformed(evt);
            }
        });

        calculateButton.setText("Calcola");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        resLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resLabel.setText("Risultato");

        pValLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pValLabel.setText("P-Value");

        pValLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pValLabel1.setText("  Esito");
        pValLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pValText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pValTextActionPerformed(evt);
            }
        });

        resText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resTextActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        alfa_01.setText("0.01");
        alfa_01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfa_01ActionPerformed(evt);
            }
        });

        alfa_05.setText("0.05");
        alfa_05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfa_05ActionPerformed(evt);
            }
        });

        alfa_1.setText("0.1");
        alfa_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfa_1ActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        errorLabel.setText("Liv. Significatività");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dimLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(resLabel)
                                            .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dimButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pValLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pValText, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                                    .addComponent(resText))
                                .addGap(55, 55, 55)
                                .addComponent(clearButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(errorLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(alfa_05)
                                        .addComponent(alfa_01)
                                        .addComponent(alfa_1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(calculateButton))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(dimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(errorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(alfa_01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(alfa_05)
                        .addGap(5, 5, 5)
                        .addComponent(alfa_1)
                        .addGap(38, 38, 38)
                        .addComponent(calculateButton)
                        .addGap(56, 56, 56)))
                .addComponent(resLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pValLabel)
                            .addComponent(pValText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pValLabel1)
                            .addComponent(resText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(clearButton)))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        n = Integer.parseInt(N.getText());
    }//GEN-LAST:event_NActionPerformed

    private void dimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dimButtonActionPerformed
        NActionPerformed(evt);
        MActionPerformed(evt);
        model.setRowCount(n);
        model.setColumnCount(m);
    }//GEN-LAST:event_dimButtonActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        m = Integer.parseInt(M.getText());
    }//GEN-LAST:event_MActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        setObserved();
        test.testChiQuadro(alfa);
        System.out.println("Pval: " + data.getPval());
        System.out.println("Esito: " + data.getRes());
        pValTextActionPerformed(evt);
        resTextActionPerformed(evt);
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void pValTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pValTextActionPerformed
        pValText.setText(String.format("%.12f", data.getPval()));
    }//GEN-LAST:event_pValTextActionPerformed

    private void resTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resTextActionPerformed
        if(data.getRes() == false)
            resText.setText("H0: i due caratteri sono indipendenti");
        else
            resText.setText("H1: i due caratteri sono dipendenti");
    }//GEN-LAST:event_resTextActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        N.setText("");
        M.setText("");
        n = m = 0;
        alfa = 0;
        model.setColumnCount(0);
        model.setRowCount(0);
        pValText.setText("");
        resText.setText("");
        alfa_01.setSelected(false);
        alfa_05.setSelected(false);
        alfa_1.setSelected(false);
        data.clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void alfa_01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfa_01ActionPerformed
        alfa = Double.parseDouble(alfa_01.getText());
        alfa_05.setSelected(false);
        alfa_1.setSelected(false);
    }//GEN-LAST:event_alfa_01ActionPerformed

    private void alfa_05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfa_05ActionPerformed
        alfa = Double.parseDouble(alfa_05.getText());
        alfa_01.setSelected(false);
        alfa_1.setSelected(false);
    }//GEN-LAST:event_alfa_05ActionPerformed

    private void alfa_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfa_1ActionPerformed
        alfa = Double.parseDouble(alfa_1.getText());
        alfa_05.setSelected(false);
        alfa_01.setSelected(false);
    }//GEN-LAST:event_alfa_1ActionPerformed

    private void setObserved(){
        data.setDim(n, m);
        for(int i = 0; i < n; i++){
            for(int j = 0; j < m; j++){
                System.out.println("frame obs: " + Long.parseLong(model.getValueAt(i,j).toString()));
                data.getObs()[i][j] = Long.parseLong(model.getValueAt(i,j).toString());
                System.out.println("data obs: " + data.getObs()[i][j]);
            }
            System.out.println("");
        }
                
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame("Chi Square Test for indipendence").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField M;
    private javax.swing.JTextField N;
    private javax.swing.JRadioButton alfa_01;
    private javax.swing.JRadioButton alfa_05;
    private javax.swing.JRadioButton alfa_1;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton dimButton;
    private javax.swing.JLabel dimLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pValLabel;
    private javax.swing.JLabel pValLabel1;
    private javax.swing.JTextField pValText;
    private javax.swing.JLabel resLabel;
    private javax.swing.JTextField resText;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
